### PR TITLE
Tweak bias stats

### PR DESCRIPTION
**Pull request by lewisblake**

### CODE REVIEW

**Comment by lewisblake** [comment]
This PR applied weights similar to what is done with mnmb, which the calculation is based on. The current values we're getting out don't really make sense, and so I think these weights need to be applied.

**Comment by AugustinMortier** [comment]
The formulas in the information page are manual work. So I can add/edit a formula in this page if you give me the information

**Comment by lewisblake** [comment]
Remove the weights part and just correct the unit. Run a test to see if weights are needed (what they are)

**Comment by lewisblake** [comment]
Gives reasonable results with just the included changes

**Review by jgriesfeller — APPROVED** [review]
Looks good

**Pull request merged**
