### PR TITLE
fix most local tests with access to lustre

### LINKED ISSUE #1037: tests with lustre-access fail
**Describe the bug**
Please provide a clear and concise description of what the bug is.
 - Pyaerocom version: main-dev
 - Computing platform: All with connection to /lustre

**To Reproduce**
1. Run tox or pytest on PPI or laptop with mounted /lustre

**Expected behavior**
All unit-tests should pass.

### PR DESCRIPTION
**Pull request by avaldebe**
- close #1037
- register pyaro fixtures, so do not need to be imported
- use fixture full name, so it does not have to be imported
- remove unused imports on tests

Please check that the test runs localy, instead of trusting CI on this PR

### CODE REVIEW

**Review by lewisblake — DISMISSED** [review]
~LGTM :rocket:~ 

Edit: reverting approval until after checking local tests.

**Review by heikoklein — CHANGES_REQUESTED** [review]
`pytest` mostly passes the tests on ppi-b with conda 3.11 environment, except
```
tests/test_geodesy.py ....XF                                             [ 17%]
...
tests/io/pyaro/test_pyaro_config.py .FFF.F...F                           [ 85%]
```
The first one is a simple FileNotFound exception since the topo01 file doesn't exist. 
All test_pyaro fail due to: 
```
E       AttributeError: 'PyaroConfig' object has no attribute 'model_dump'

/home/heikok/tmp/pyaerocom/pyaerocom/io/pyaro/pyaro_config.py:39: AttributeError
```

**Comment by lewisblake** [comment]
What I find when I run on ppi-r8login with a fresh installation:

```console
=============================================================================================================================================== short test summary info ================================================================================================================================================
FAILED tests/io/test_readungridded.py::test_supported - AssertionError: assert {'AeronetInvV...2.daily', ...} <= {'AeronetInvV...2.daily', ...}
FAILED tests/plugins/test_entry_points.py::test_gridded - AssertionError: no entry points found
FAILED tests/plugins/test_entry_points.py::test_ungridded - AssertionError: no entry points found
FAILED tests/test_colocation_auto.py::test_colocator_instantiate_gridded_reader - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
FAILED tests/test_colocation_auto.py::test_colocator_instantiate_gridded_reader_model_data_dir - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
FAILED tests/test_colocation_auto.py::test_colocator__get_gridded_reader_class - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
FAILED tests/test_colocation_auto.py::test_colocation_pyaro - KeyError: 'concso4'
FAILED tests/test_colocation_auto.py::test_colocation_pyaro_change_obs_id - KeyError: 'concso4'
FAILED tests/test_geodesy.py::test_etopo_altitude - FileNotFoundError: [Errno 2] No such file or directory: '/home/lewisb/.geonum/ETOPO1_Ice_g_gmt4.grd'
```

**Comment by avaldebe** [comment]
> ```
> FAILED tests/io/test_readungridded.py::test_supported - AssertionError: assert {'AeronetInvV...2.daily', ...} <= {'AeronetInvV...2.daily', ...}
> FAILED tests/plugins/test_entry_points.py::test_gridded - AssertionError: no entry points found
> FAILED tests/plugins/test_entry_points.py::test_ungridded - AssertionError: no entry points found
> ```

these errors are a direct result of the entry points not been registered properly 

> ```
> FAILED tests/test_colocation_auto.py::test_colocator_instantiate_gridded_reader - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
> FAILED tests/test_colocation_auto.py::test_colocator_instantiate_gridded_reader_model_data_dir - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
> FAILED tests/test_colocation_auto.py::test_colocator__get_gridded_reader_class - NotImplementedError: Reader ReadMscwCtm is not supported: 'ReadMscwCtm'
> FAILED tests/test_colocation_auto.py::test_colocation_pyaro - KeyError: 'concso4'
> FAILED tests/test_colocation_auto.py::test_colocation_pyaro_change_obs_id - KeyError: 'concso4'
> ```

these are a side effect of the missing readers (which were defined as entry points)

> ```
> FAILED tests/test_geodesy.py::test_etopo_altitude - FileNotFoundError: [Errno 2] No such file or directory: '/home/lewisb/.geonum/ETOPO1_Ice_g_gmt4.grd'
> ```

some of the test on this module are broken/unreliable, see #1050 for a follow up.

I plan to deal with the broken entry points on a separate PR, ~~so I'll mark this PR as a draft until that is fixed.~~

**Comment by avaldebe** [comment]
> tests/io/pyaro/test_pyaro_config.py

these tests are passing locally for me, please check again

**Comment by heikoklein** [comment]
My failing tests were caused by pydantic1, pydantic>2 solves the problem (hopefully). To be solve in another issue. Closing and merging.

**Review by heikoklein — APPROVED** [review]

**Comment by heikoklein** [comment]
working with pydantic > 2

**Pull request merged**
