### PR TITLE
Revise logic related to outlier removal in low and high level colocation routines

### PR DESCRIPTION
**Pull request by jgliss**
Related to #50 and #296.

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna I reorganised a little the handling of outlier removals in colocation routines. This comes with minor changes in the API, that is, if you want to set outlier ranges for obs explicitly in a config file, you should use `obs_outlier_ranges` instead of `var_ref_outlier_ranges` (even though the old way should still work as well). And if you happen to want to remove outliers from models (which I never do), you can specify that via `model_remove_outliers` (as `remove_outliers` will only be applied to obs, as before). 

Most importantly, outlier removal is now done in Colocator and the lowlevel colocation functions do not support outlier removal anymore.

Can you briefly review please? 

Cheers, 
Jonas

**Comment by jgliss** [comment]
@hansbrenna next one ready for review :) would you be able to check it out? Many thanks in advance!

**Review by hansbrenna — APPROVED** [review]
Good to clean up the outlier handling. It was redundant before :)

**Comment by jgliss** [comment]
> Good to clean up the outlier handling. It was redundant before :)

Thanks!

**Pull request merged**
