### PR TITLE
Use PyPis Trusted Publisher Management for releases

### LINKED ISSUE #972: Use PyPis Trusted Publisher Management for releases
Publish to pypi uses currently the token based publishing code at:
https://github.com/metno/pyaerocom/blob/main-dev/.github/workflows/publish.yml

Tokens can be stolen and thus the code at pypi can be modified without recognition. PyPi and github prefer therefore PyPis Trusted Publisher Management.

Steps required:
In publish.yml:
add after `runs-on: ubuntu-latest`
```yml
    environment: release
    permissions:
      id-token: write
```
remove
```yml
  with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
```

In github:
  * remove secret PYPI_API_TOKEN
  * add `release` environment

In pypi:
  * remove api-tokens under Account Settings
  * under Projects -> pyaercom -> Publishing: Add new publisher (the github-repo, release env, and publish.yml)

### PR DESCRIPTION
**Pull request by lewisblake**
Designed to close #972 

https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/

- [x] Update `publish-yml`
- [x] In github:
     - [x] remove secret PYPI_API_TOKEN
     - [x] add release environment 
- [x] In pypi:
     - [x] remove api-tokens under Account Settings
     - [x] under Projects -> pyaercom -> Publishing: Add new publisher (the github-repo, release env, and publish.yml)

### CODE REVIEW

**Comment by heikoklein** [comment]
Looks good so far.

**Comment by lewisblake** [comment]
This step: *remove api-tokens under Account Settings* wasn't needed because we didn't have any or they had been removed already.

**Comment by heikoklein** [comment]
Without api-token and without trusted publisher, new versions must have been uploaded manually before?

**Comment by heikoklein** [comment]
Checked now the pypi history and the latest versions were added by @avaldebe using an API-token. Maybe the API-token is only visible for him, then he should remove it.

**Comment by heikoklein** [comment]
API token created
Permissions: Can upload to this project
Controlled by: [avaldebe](https://pypi.org/user/avaldebe/)
Token name: gh-actions-pyaerocom
	Oct 22, 2021, 1:42:01 PM 	157.249.105.7
No User-Agent

**Review by heikoklein — APPROVED** [review]

**Comment by heikoklein** [comment]
I restricted the 'release' environment to be restricted to tags with name `v*.*.*` (which is pyaerocom convention anyway). Just to avoid accidential tags to get released.

**Pull request merged**
