### PR TITLE
temperature from ebas

### LINKED ISSUE #788: Temperature data
As part of the [observations explorer](https://aeroval.met.no/evaluation.php?project=obs) project, it would be great to have temperature data, in addition to the already supported precipitations. Those two variables could be part of the 'meteorology' experiment.
EBAS provide temperature data over Europe.

### PR DESCRIPTION
**Pull request by avaldebe**
close #788

### CODE REVIEW

**Review by lewisblake — APPROVED** [review]
:abacus:

**Comment by lewisblake** [comment]
I was quite convinced that CI would pass for the remaining Python version earlier so I approved these changes. Perhaps I was too hasty

**Comment by avaldebe** [comment]
> I was quite convinced that CI would pass for the remaining Python version earlier so I approved these changes. Perhaps I was too hasty

`conda` failed to resolve the dependencies for Python 3.11, so it was a `pyaerocom` failure. Will look into this tomorrow.

**Comment by lewisblake** [comment]
> > I was quite convinced that CI would pass for the remaining Python version earlier so I approved these changes. Perhaps I was too hasty
> 
> `conda` failed to resolve the dependencies for Python 3.11, so it was a `pyaerocom` failure. Will look into this tomorrow.

Indeed 
```console
  Package click conflicts for:
  dask -> dask-core[version='>=2022.11.1,<2022.11.2.0a0'] -> click[version='>=6.6,<8.0.0|>=6.6,<8.1.0|>=6.6|>=7.0']
  typer[version='>=0.4.0'] -> click[version='>=7.1.1,<9|>=7.1.1,<9.0.0']
  iris[version='>=3.2.0'] -> dask-core[version='>=2'] -> click[version='>=7.0']The following specifications were found to be incompatible with your system:
```

**Comment by lewisblake** [comment]
:fireworks:

**Pull request merged**
