### PR TITLE
Updates needed to combine several observations into one superobservation

### PR DESCRIPTION
**Pull request by jgliss**
Needed in CAMS84 to combine EEA, AirNow and chinese (MarcoPolo) data into a single super-obs network. 

**NOTE**: this PR will also includes some updates related to menu creation of the web tools, for instance, to have more control on the order of observations and models in menu and heatmap display.

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna could you review this PR please? I think it makes sense that you do it as there are some changes that may affect your developments as well, and new features that may be interesting for you. Thanks!

**Comment by jgliss** [comment]
@hansbrenna will you be able to look at this now? Or should I just merge (we can also review once dev-cams84 goes into main-dev).

**Comment by hansbrenna** [comment]
There's a lot here that is really interesting. It looks safe to merge to me.

**Review by hansbrenna — APPROVED** [review]

**Comment by jgliss** [comment]
> There's a lot here that is really interesting. It looks safe to merge to me.

Thanks for checking!

**Pull request merged**
