### PR TITLE
drop Python 3.9 support

### LINKED ISSUE #1034: Remove support for python 3.9
**Is your feature request related to a problem? Please describe.**
We are no longer running any projects with python3.9, and compatibility with 3.9 is sometimes hard to maintain, e.g. with respect to typing.

**Describe the solution you would like to see**
Remove python-3.9 from tests and dependencies.

**Additional context**
This will also improve the speed of CI-tests, since 2 of 8 bigger tests are removed.

### PR DESCRIPTION
**Pull request by avaldebe**
close #1034

### CODE REVIEW

**Comment by avaldebe** [comment]
some commits not intended for this branch/PR went trough, I'll clean up the PR

**Comment by avaldebe** [comment]
ready for review

**Review by heikoklein — CHANGES_REQUESTED** [review]
conflict for docs between 3.9 and 3.10, see tests

**Comment by heikoklein** [comment]
in .readthedocs.yaml:
``` 
tools:
    python: "3.9"
```

**Comment by avaldebe** [comment]
> conflict for docs between 3.9 and 3.10, see tests

fixed

**Comment by avaldebe** [comment]
> in .readthedocs.yaml:
> 
> ```
> tools:
>     python: "3.9"
> ```

fixed

**Review by heikoklein — APPROVED** [review]

**Pull request merged**
