### PR TITLE
Versionflag496

### PR DESCRIPTION
**Pull request by lewisblake**
Not to get too hasty, but I wanted to get a continue the conversation around this feature (#496), and comments, code reviews, etc., seem like a good way to go about it.

@avaldebe You mentioned using typer in your linked comment. I wanted to see if you still think we should go that route to re-implement `pyaerocom.scripts.cli` or whether something simple works for now. Currently it seems like pyaerocom doesn't depend on typer and so going that direction seems like a bigger modification. Also not sure if tests are run on CLIs / if possible

### CODE REVIEW

**Comment by avaldebe** [comment]
> @avaldebe You mentioned using typer in your linked comment. I wanted to see if you still think we should go that route to re-implement `pyaerocom.scripts.cli` or whether something simple works for now. Currently it seems like pyaerocom doesn't depend on typer and so going that direction seems like a bigger modification. Also not sure if tests are run on CLIs / if possible

This CLI is very simple, so you can implement the extra option using `argparse.ArgumentParser`.

**Comment by lewisblake** [comment]
Putting testing CLI on the back-burner for now. Can revisit if we think it's worth it and I have more time

**Comment by lewisblake** [comment]
A simple implementation of the --version flag for the CLI. Made my Typer-base implementation a different branch and we can look at the separately.

**Comment by lewisblake** [comment]
Typer-based CLI alternative #624

**Pull request closed without merging**
