### PR TITLE
draft of applying mon->yr constraints when calculating overall statistics

### PR DESCRIPTION
**Pull request by hansbrenna**
This might be a neat solution. Use the non-NaN stations in the `yearly` colcoacated data object to select the stations used when calculating the heatmap statistics.

### CODE REVIEW

**Comment by hansbrenna** [comment]
There are still some issues I need to work out. Right now it only works for 'WORLD' for some reason

**Comment by jgliss** [comment]
Great that you work on this. However, this needs to be an option that can be specified in the config file, and by default, it should do it without applying this yearly constraint (you can then activate the option for cams61)!

**Review by jgliss — CHANGES_REQUESTED** [review]
Indeed, this seems to be a neat way of doing this, but make sure it is optional in the config file, and default processing should do it the way it used to do it. Perhaps add a boolean attr `annual_stats_constrained` (or similar) in the `AerocomEvaluation` class, defaulting to `False`.

**Comment by hansbrenna** [comment]
I agree

**Comment by hansbrenna** [comment]
The bug that makes it work only for WORLD seems to be in my main branch.

**Comment by jgliss** [comment]
@hansbrenna consider making this a draft PR until the feature is ready.

**Comment by jgliss** [comment]
@hansbrenna I think I have something which I would call BETA finished ;) I guess, you should probably revise what I did here. It seems to work for the colocated data file you sent me and CI also passes (even though this does not yet include tests for the new option).

**Comment by jgliss** [comment]
@hansbrenna I think the failing CI here is for the PR is due to failing tests in `Hans_main_dev`, for `dev-annual-limit` all tests seem to pass now.

**Review by jgliss — APPROVED** [review]
@hansbrenna I had a quick look over what we did here and it seems okay. Please review as well, since I also modified quite a bit here. Cheers!

**Review by hansbrenna — COMMENTED** [review]
I think this looks fine. I will merge it now.

**Pull request merged**
