### PR TITLE
Split map files by year

### PR DESCRIPTION
**Pull request by lewisblake**
Closing #756

### CODE REVIEW

**Comment by dulte** [comment]
Have you tested this for periods of more than one year? E.g. 2010-2020.

**Comment by lewisblake** [comment]
On the Aeroval side, @AugustinMortier will be testing the results from a run from this afternoon over 2018-2020 using this set up shortly. Perhaps it would be best to wait and see how this change effects the website before merging.

**Comment by lewisblake** [comment]
@AugustinMortier says it works on the Aeroval side

**Review by dulte — APPROVED** [review]
Then you can merge :)

**Pull request merged**
