### PR TITLE
Add pages argument to WebDisplayOpts class

### LINKED ISSUE #965: Better configurability of the aeroval pages
Right now, there is a default set of AeroVal pages rendered for each experiment:
- maps.php
- evaluation.php
- intercomp.php
- overall.php
- infos.php

This list is harcoded in AeroVal.

Now, there are two options in the config files within the `webdisp_opts` key: 
- hide_pages
- add_pages

which are arrays made of the page names to be hidden or added
e.g:
```
"hide_pages": [
         "maps.php",
         "intercomp.php",
         "overall.php"
]
```

In order to clarify what will be available online eventually, it would better to have a single entry describing which pages are supposed to be rendered.
e.g: 
```
"pages": ["maps", "evaluation", "intercomp", "overall", "infos"]
```

We suggest to use page "keys" ("evaluation") instead of page names ("evaluation.php") in case the pages are renamed later.
The mapping will be performed by AeroVal itself.

The suggested keys are:
- maps (default)
- evaluation (default)
- intercomp (default)
- overall (default)
- infos (default)
- cams2-82_reports (optional)
- cams2-83_reports (optional)

### PR DESCRIPTION
**Pull request by lewisblake**
Closes #965. Based on the requirements presented there, a default it set to `["maps", "evaluation", "intercomp", "overall", "infos"]`. If this default is overridden by providing a `pages` argument, **all** the pages which are intended to show up on the web must be provided.

### CODE REVIEW

**Comment by AugustinMortier** [comment]
Looks good. I juste have to implement the logic on the frontend. From which pyaerocom version should I expect this new format?

Also, one current user of this feature is CAMS2_2 that adds reports page. So, it should be explained, to people running those experiments, how they need to modify their config files.

**Comment by lewisblake** [comment]
> Looks good. I juste have to implement the logic on the frontend. From which pyaerocom version should I expect this new format?

Great.  >v0.16.0 should have this feature implemented.

> Also, one current user of this feature is CAMS2_2 that adds reports page. So, it should be explained, to people running those experiments, how they need to modify their config files.

I will speak to @andagit about how to modify her config files.

Can you approve this, @AugustinMortier if you are okay with it? Thanks.

**Comment by lewisblake** [comment]
@AugustinMortier will the website be able to handle this before the next release (Tuesday 9.4.24)? Some attention now needs to be given to this PR since there are conflicts

**Comment by AugustinMortier** [comment]
It will be ready for the release after, I think. We need to finalize the
deployment of the API version of AeroVal on the main server first.

**Comment by lewisblake** [comment]
@AugustinMortier Any updates on this?

**Comment by AugustinMortier** [comment]
Not yet, sorry. Busy with other projects and initiating the API documentation. I'll try to have a look next week!

**Comment by AugustinMortier** [comment]
The front end now supports the `pages` option.
Working example [here](https://aeroval.met.no/pages/evaluation/?project=testing&experiment=pages&station=ALL)

**Comment by AugustinMortier** [comment]
It would probably make sense to "connect" a little the list of pages in the config file to the actual pyaerocom computation: e.g, if the contour plots have not been processed, but the 'maps' page is in the list of visible pages, the user should have at least a warning (so we avoid ending up with empty pages)..?

**Review by AugustinMortier — APPROVED** [review]

**Pull request merged**
