### PR TITLE
New minimaldata

### PR DESCRIPTION
**Pull request by dulte**
## Change Summary

Adds the hash for the new testdata minimal which includes a new EMEP file with data for 1999

## Related issue number

Related to https://github.com/metno/pyaerocom-tutorials/issues/19 

## Checklist

* [x] Start with a draft-PR
* [x] The PR title is a good summary of the changes
* [x] PR is set to AeroTools and a tentative milestone
* [x] Documentation reflects the changes where applicable
* [x] Tests for the changes exist where applicable
* [x] Tests pass locally
* [x] Tests pass on CI
* [x] At least 1 reviewer is selected
* [x] Make PR ready to review

### CODE REVIEW

**Comment by lewisblake** [comment]
Would you be willing to include another file in this minimal data? We talked about updating this yesterday anyway. I'll email you the file

**Comment by dulte** [comment]
> Would you be willing to include another file in this minimal data? We talked about updating this yesterday anyway. I'll email you the file

Sure. I'll add it immediately :)

**Comment by dulte** [comment]
@lewisblake your file can now be found under `/modeldata/colocated_netcdf/my_colocated_data.nc`. It was quite large, so I cut it down to just 1 year. I hope that is OK?

**Comment by lewisblake** [comment]
Awesome, thanks!

**Comment by lewisblake** [comment]
This PR will help with https://github.com/metno/pyaerocom-tutorials/issues/20 also

**Review by heikoklein — APPROVED** [review]

**Pull request merged**
