### PR TITLE
Add reading routine for AirNow obs dataset

### PR DESCRIPTION
**Pull request by jgliss**
Most of it is done, for details see here:

https://github.com/metno/pyaerocom-dev-scripts/pull/1

### CODE REVIEW

**Comment by jgliss** [comment]
What is missing:

- [ ] Incorporate in paths.ini and register in ReadUngridded
- [ ] add docstrings
- [ ] Add tests
- [ ] Run test evaluation for CAMS84

**Comment by jgliss** [comment]
@AugustinMortier we need to check the variable unit assignments, for instance, what you identified as "concbc" (BC in the files) has units of ug m-2 so it seems to be deposition or similar...

**Comment by jgliss** [comment]
@AugustinMortier forget it. I was wrong, typo in the code^^

**Comment by jgliss** [comment]
@AugustinMortier but we do need to check the variable names for the current set of variables, e.g. conco3 really is vmro3 (units of ppb)

**Comment by jgliss** [comment]
@AugustinMortier I updated variable names, fixed weird station names in the data (some had / in it which screwed with the json files) and added tests, currently running the automatic tools for CAMS84 web interface, which will hopefully work now. Could you review once more the recent updates?

**Comment by jgliss** [comment]
@AugustinMortier AirNow vs OSUITE first test just finished and looking good (from a quick view): 

https://aerocom-evaluation.met.no/main.php?project=cams84&exp=eval-2020

**Review by AugustinMortier — APPROVED** [review]
Looks good!

**Comment by jgliss** [comment]
> Looks good!

Takk!

**Pull request merged**
