### PR TITLE
clean up MEP reader

### PR DESCRIPTION
**Pull request by avaldebe**
follow up from #784

### CODE REVIEW

**Review by lewisblake — APPROVED** [review]
Ser veldig bra ut!

**Review by lewisblake — APPROVED** [review]
Looks even better. Did you notice any performance changes?

**Comment by avaldebe** [comment]
> Looks even better. Did you notice any performance changes?

It is a bit faster, but nothing considerable

**Comment by avaldebe** [comment]
@dulte 
I would appreciate if you can have a look at the `MEP` (formerly `HARP`) reader.
In particular, I would like your opinion on the `dtime` settings.
Currently it uses the `datetime_start` field, but maybe it should use the `datetime_end` or the the average of both (time at the middle of the period).

**Review by lewisblake — APPROVED** [review]

**Pull request merged**
