### PR TITLE
try new syntax to exclude mda8 from maps

### LINKED ISSUE #1324: mda8 is not computed for the maps
at least for cams2_83, running with @cams2_83-202408:  
in the output in the `contour` folder we expect 1 file per variable per model and no files for conco3mda8 are produced there
see e.g. `/lustre/storeB/project/fou/kl/CAMS2_83/evaluation/data/cams2-83/forecast-current-season/contour/`  
the api also then throws an error accordingly and there is no data to show https://regional-evaluation.atmosphere.copernicus.eu/pages/maps/?project=cams2-83&experiment=forecast-last-week&station=ALL&parameter=conco3mda8&frequency=daily

### PR DESCRIPTION
**Pull request by charlienegri**
previous fix breaks menu.json, wrong syntax

## Related issue number

trying to close #1324

## Checklist

* [x] Start with a draft-PR
* [x] The PR title is a good summary of the changes
* [x] PR is set to AeroTools and a tentative milestone
* [x] Documentation reflects the changes where applicable
* [x] Tests for the changes exist where applicable
* [x] Tests pass locally
* [x] Tests pass on CI
* [x] At least 1 reviewer is selected
* [x] Make PR ready to review

### CODE REVIEW

**Comment by charlienegri** [comment]
I have not tested this yet

**Comment by charlienegri** [comment]
tested this and I do not see the variables in the map menu still even though menu.json looks correct now
https://aeroval-test.met.no/charlien/pages/maps/?project=cams2-83&experiment=test-forecast-week-2&station=ALL

this the relevant bit of menu.json
```
"conco3mda8": {
        "type": "3D",
        "cat": "Gas concentrations",
        "name": "O3 MDA8",
        "obs": {
            "EEA-UTD": {
                "Surface": {
                    "ENSEMBLE": {
                        "model_id": "CAMS2-83.ENSEMBLE.day0.FC",
                        "model_var": "conco3mda8",
                        "obs_var": "conco3mda8"
                    },
                    "CHIMERE": {
                        "model_id": "CAMS2-83.CHIMERE.day0.FC",
                        "model_var": "conco3mda8",
                        "obs_var": "conco3mda8"
                    },
                    ........
                    "SILAM": {
                        "model_id": "CAMS2-83.SILAM.day0.FC",
                        "model_var": "conco3mda8",
                        "obs_var": "conco3mda8"
                    }
                }
            }
        },
        "longname": "MDA8 of O3 mass concentration",
        "only_use_in": [
            "evaluation",
            "intercomp",
            "overall"
        ]
    },

```

**Comment by charlienegri** [comment]
> tested this and I do not see the variables in the map menu still even though menu.json looks correct now https://aeroval-test.met.no/charlien/pages/maps/?project=cams2-83&experiment=test-forecast-week-2&station=ALL
> 

this might be due to the frontend behavior, Augustin will check

**Comment by charlienegri** [comment]
the fronted is fixed, so this syntax works and has been tested

**Review by thorbjoernl — APPROVED** [review]

**Pull request merged**
