### PR TITLE
Fix ebas automatic column selection 

### PR DESCRIPTION
**Pull request by jgliss**
see #345

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna this should fix the OC reading. Please, can you review?

Note, that this will increase the verbosity in EBAS reading in case such unresolvable conflicts occur when inferring the correct column. Something I want to have for now to be able to reiterate the logic here.

**Review by hansbrenna — APPROVED** [review]

**Comment by jgliss** [comment]
@hansbrenna thanks for reviewing. I will add a few more tests before I merge this!

**Comment by jgliss** [comment]
Making this a draft for now, as we need to think about this a little more, e.g., how to deal with situations where multiple column matches denote different measurement heights:

```bash
Data period: 2018-01-01T00:30:00 - 2018-12-31T23:29:59),
Station Kosetice (NOAK) (col matches: [2, 6, 10])
Column 2
name: ozone, unit: ug/m3, is_var: True, is_flag: False, flag_col: 3, tower_inlet_height: 50.0 m, measurement_height: 50.0 m, instrument_name: uv_abs_kre_0050, instrument_serial_number: 1218153724, volume_std._temperature: 293.15 K, volume_std._pressure: 1013.25 hPa, detection_limit: 1.995 ug/m3, "comment: Data converted on import into EBAS from 'nmol/mol' to 'ug/m3' at 293.15 K
Column 6
name: ozone, unit: ug/m3, is_var: True, is_flag: False, flag_col: 7, tower_inlet_height: 8.0 m, measurement_height: 8.0 m, instrument_name: uv_abs_kre_0125, instrument_serial_number: 1218153723, volume_std._temperature: 293.15 K, volume_std._pressure: 1013.25 hPa, detection_limit: 1.995 ug/m3, "comment: Data converted on import into EBAS from 'nmol/mol' to 'ug/m3' at 293.15 K
Column 10
name: ozone, unit: ug/m3, is_var: True, is_flag: False, flag_col: 11, tower_inlet_height: 230.0 m, measurement_height: 230.0 m, instrument_name: uv_abs_kre_0230, instrument_serial_number: 1218153722, volume_std._temperature: 293.15 K, volume_std._pressure: 1013.25 hPa, detection_limit: 1.995 ug/m3, "comment: Data converted on import into EBAS from 'nmol/mol' to 'ug/m3' at 293.15 K
Filename: CZ0003R.20180101000000.20191216134000.uv_abs.ozone.air.1y.1h..CZ06L_uv_abs.lev2.nas
```

**Comment by hansbrenna** [comment]
I have tested concso4 from EBAS and there are the same kinds of problems there. Adding the output here for documentation purposes. Out of 5252 files 913 could not be read.

Screenshot from 2021-03-16 13-40-22

**Review by hansbrenna — APPROVED** [review]

**Comment by jgliss** [comment]
@hansbrenna this is ready for review I think (I will take care of the test coverage after merging into main-dev and before we release 0.11.0).

**Review by hansbrenna — APPROVED** [review]
Looks fine.

**Pull request merged**
