### PR TITLE
Adding glob_stats_yearly.json

### PR DESCRIPTION
**Pull request by hansbrenna**
This enables calculation of glob_stats_yearly.json which includes the spatial correlations as R/R_spearman

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna is this a draft PR or should I review this maybe?

**Review by jgliss — CHANGES_REQUESTED** [review]
Looks good, however, you should probably register the new file add it to method `AerocomEvaluation._heatmap_files`.

**Comment by hansbrenna** [comment]
Thanks. I will do that.

**Review by jgliss — APPROVED** [review]
Looks good!

**Pull request merged**
