### PR TITLE
Dev mod mod coloc

### PR DESCRIPTION
**Pull request by hansbrenna**
Further development of model-model colocation.

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna what about this branch?

**Comment by jgliss** [comment]
@hansbrenna what about this PR? Will you be able to finish this for release of 0.12.0?

**Comment by hansbrenna** [comment]
I started this when I thought I would need it for CAMS61. I ended up not needing it and I don't think I will need it in the near future. If this is a prioritized feature I should be able to implement it (I think)

**Comment by jgliss** [comment]
Can you check if there is anything that you already did, that should be digested in main-dev? If not, feel free to close this PR and perhaps create an issue, if mod / mod co-location still does not work.

**Comment by hansbrenna** [comment]
@avaldebe no.

**Pull request closed without merging**
