### PR TITLE
Evaluation of concentration in precipitation and wet deposition

### PR DESCRIPTION
**Pull request by jgliss**

### CODE REVIEW

**Comment by jgliss** [comment]
@hansbrenna this branch contains the code for computing `concprcpX` from `wetX` and `pr`, which can then be used to compare with e.g. EBAS observations. Can you test this code? It will probably need some debugging still, but I managed to run 

https://aerocom-evaluation.met.no/main.php?project=examples&exp=test-wetprcp

The corresponding config file (as json) is here: 

https://aerocom-evaluation.met.no/data/json/examples/test-wetprcp/cfg_examples_test-wetprcp.json

I am currently rerunning this with the updated EBAS dataset (takes a while to reload) and specifying outlier ranges. 

Can you test if this works with the other models? 

Cheers

**Comment by jgliss** [comment]
@hansbrenna I only tested this for `concprcpoxn`, which is `concprcpno3`, therefore the entry in model_config: 

```python
MOD_LOCAL = '/home/jonasg/MyPyaerocom/data/modeldata/'

concprcp_read_add = dict(
    concprcpoxn = dict(
        try_convert_units   =   False,
        aux_add_args        =   dict(ts_type='monthly',
                                     prlim=0.1e-3,
                                     prlim_units='m d-1',
                                     prlim_set_under=np.nan)
    )
    )

MODELS = {
    'EMEP-u3all'    : dict(model_id='EMEP-cams50-u3all',
                           model_data_dir=MOD_LOCAL+'EMEP-cams50-u3all/renamed',
                           model_use_vars={'concprcpno3' : 'concprcpoxn'},
                           model_read_opts=concprcp_read_add)
}

OBS_GROUNDBASED = {

    'EBAS'    :   dict(obs_id='EBASMC',
                       obs_vars=['concprcpno3'],
                       obs_vert_type='Surface',
                       obs_filters = dict(remove_outliers = True,
                                         set_flags_nan   = True,
                                         data_level      = 2),
                       var_outlier_ranges = {
                           'concprcpno3'   :   [1e3, 1e7]
                           }
                       ),
}
```

**Comment by jgliss** [comment]
Other variables (e.g. `concprcpso4`) still need to be registered in the header of ReadGridded (AUX_REQUIRES and AUX_FUNS).

**Comment by jgliss** [comment]
@hansbrenna I just add concprcpoxs in the header of ReadGridded (I guess this is supposed to be compared with EBAS concprcpso4, but maybe briefly double-check with Hilde). I also changed some details in the computation methods related to the unit definitions in the models - EMEP uses implicit units for wdep and pr, e.g. kg N m-2 and mm while most other models use kg N m-2 h-1 an mm h-1, and so far I had only tested the EMEP case. I think you need to merge the most recent changes for the code to work on models other than EMEP.

**Comment by jgliss** [comment]
@hansbrenna I did some more debugging of the code and added some missing variables and unit aliases. I think it should work now, currently running all models from rerun experiment in our "examples" project, both `concprcpoxn` and `concprcpoxs`. But is reeeeally slow via vpn, hope it is finished by tomorrow morning. I will copy below the config file that I just set up for that, perhaps that helps you to incorporate it in your cfg. Cheers

**Comment by jgliss** [comment]
```python
add_read = dict(
        try_convert_units   =   False,
        aux_add_args        =   dict(ts_type='monthly',
                                     prlim=0.1e-3,
                                     prlim_units='m d-1',
                                     prlim_set_under=np.nan)
    )
concprcp_read_add = dict(
    concprcpoxn = add_read,
    concprcpoxs = add_read
    )

MODELS = {
    'EMEP-u3all'    : dict(model_id='EMEP.cams50.u3all',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),
    'EMEP'          : dict(model_id='EMEP.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'CHIMERE'       : dict(model_id='CHIMERE.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),
    'SILAM'         : dict(model_id='SILAM.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'MONARCH'         : dict(model_id='MONARCH.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'EURAD-IM'         : dict(model_id='EURAD-IM.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'MINNI'         : dict(model_id='MINNI.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'DEHM'         : dict(model_id='DEHM.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add),

    'LOTOSEUROS'         : dict(model_id='LOTOSEUROS.cams61.rerun',
                           model_use_vars={'concprcpno3' : 'concprcpoxn',
                                           'concprcpso4' : 'concprcpoxs'},
                           model_read_opts=concprcp_read_add)
}

OBS_GROUNDBASED = {

    'EBAS'    :   dict(obs_id='EBASMC',
                       obs_vars=['concprcpso4', 'concprcpno3'],
                       obs_vert_type='Surface',
                       obs_filters = dict(remove_outliers = True,
                                          set_flags_nan   = True,
                                          data_level      = 2),
                       var_outlier_ranges = {
                           'concprcpno3'   :   [1e3, 1e7],
                           'concprcpso4'   :   [1e3, 1e7]
                           }
                       ),
}

REGRID_SAT = dict(lat_res_deg=5,
                  lon_res_deg=5)
OBS_SAT = {
}

BASE_CFG = dict(

    out_basedir = os.path.abspath('../json/'),
    add_methods_file = os.path.abspath('../eval_py/cube_read_methods.py'),

    # if True, existing colocated data files will be deleted
    reanalyse_existing = True,

    clear_existing_json = False,

    # if True, the analysis will stop whenever an error occurs (else, errors that
    # occurred will be written into the logfiles)
    raise_exceptions = False,

    # Regional filter for analysis
    filter_name = 'WORLD-wMOUNTAINS',

    ts_type = 'daily',

    start = 2018,

    colocate_time=False, # where applicable, colocate model with obs in highest possible time resolution before resampling
    apply_time_resampling_constraints=True,

    remove_outliers=False,
    harmonise_units=True,
    model_keep_outliers=True,

    var_order_menu = ['ang4487aer', 'od550aer', 'od550lt1aer', 'od550gt1aer',
                      'abs550aer', 'ac550aer', 'sc550dryaer'],
    var_mapping = VAR_MAPPING

)

COL_BASE = os.path.abspath('../../coldata/examples/')

EXP_ID = 'test-wetprcp'

PROJ_SPECS = dict(

proj_id = 'examples',

#: ID and name of experiment
exp_id = EXP_ID,
exp_name = 'Example run to test concprcp evaluation in CAMS61',
# =============================================================================
# exp_descr = ('This experiment is supplementary to the Gliss et al., 2020 paper '
#              '(https://acp.copernicus.org/preprints/acp-2019-1214/). It contains '
#              'all models and observation datasets (and corresponding variables) '
#              'that have been evaluated in the paper. Note, this interface '
#              'only contains the results from the model / obs comparisons '
#              '(Sect. 4 in revised manusrcript) and not the results from the '
#              'lifecycle analysis.'),
#
# exp_status = 'public',
# =============================================================================
# directory where colocated data files are supposed to be stored
basedir_coldata = os.path.join(COL_BASE, EXP_ID),
weighted_stats = True

)

CFG = {}
CFG.update(PROJ_SPECS)
CFG.update(BASE_CFG)

CFG['model_config'] = {}
CFG['model_config'].update(MODELS)

CFG['obs_config'] = {}
CFG['obs_config'].update(OBS_GROUNDBASED)
CFG['obs_config'].update(OBS_SAT)
```

**Comment by jgliss** [comment]
@hansbrenna just added another "custom" unit

**Comment by jgliss** [comment]
Reminder: need to apply PR #280 first.

**Comment by jgliss** [comment]
@hansbrenna this is the branch for the wetdep analysis. Updated also time resampler from ceil to round (not floor), that is, if e.g. daily -> weekly is set to 5 days per week, for 6daily it will be int(round(5/6))=1

**Comment by jgliss** [comment]
@hansbrenna I just pushed an update that will hopefully fix the 6daily issue in EBAS...

**Comment by jgliss** [comment]
@hansbrenna this is the config file I used for wetdep eval atest shown here: 

https://aerocom-evaluation.met.no/main.php?project=examples&exp=test-wetdep

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Config file for AeroCom Evaluation interface
"""
import os
import numpy as np
import pyaerocom as pya
from pyaerocom.web import VAR_MAPPING

pya.const.add_data_search_dir(pya.const.OUTPUTDIR + '/data/modeldata')
ebas_local = os.path.join(pya.const.OUTPUTDIR, 'data/obsdata/EBASMultiColumn/data')

MODELS = {
    'EMEP-u3all'    : dict(model_id='EMEP.cams50.u3all'),
    'EMEP'          : dict(model_id='EMEP.cams61.rerun'),
    'CHIMERE'       : dict(model_id='CHIMERE.cams61.rerun'),
    'SILAM'         : dict(model_id='SILAM.cams61.rerun'),
    'MONARCH'       : dict(model_id='MONARCH.cams61.rerun'),
    'EURAD-IM'      : dict(model_id='EURAD-IM.cams61.rerun'),
    'MINNI'         : dict(model_id='MINNI.cams61.rerun'),
    'DEHM'          : dict(model_id='DEHM.cams61.rerun'),
    'LOTOSEUROS'    : dict(model_id='LOTOSEUROS.cams61.rerun')
}

OBS_GROUNDBASED = {

    'EBAS'    :   dict(obs_id='EBASMC',
                       obs_vars=['wetoxs', 'wetoxn',
                                 'wetrdn'],
                       obs_vert_type='Surface',
                       obs_filters = dict(set_flags_nan   = True,
                                          data_level      = 2),
                       obs_data_dir=ebas_local,
                       ),
}

REGRID_SAT = dict(lat_res_deg=5,
                  lon_res_deg=5)
OBS_SAT = {
}

BASE_CFG = dict(

    out_basedir = os.path.abspath('../json/'),
    add_methods_file = os.path.abspath('../eval_py/cube_read_methods.py'),

    # if True, existing colocated data files will be deleted
    reanalyse_existing = False,

    clear_existing_json = False,

    # if True, the analysis will stop whenever an error occurs (else, errors that
    # occurred will be written into the logfiles)
    raise_exceptions = False,

    # Regional filter for analysis
    filter_name = 'WORLD-wMOUNTAINS',

    ts_type = 'daily',

    start = 2018,

    colocate_time=False, # where applicable, colocate model with obs in highest possible time resolution before resampling
    apply_time_resampling_constraints=False,

    min_num_obs = dict(

        daily      =   dict(hourly      = 6),
        monthly    =   dict(daily       = 7, # from Hilde's EMEP plot for CAMS50 EMEP u3all
                            weekly      = 1),
        yearly     =   dict(monthly     = 3)

    ),
    remove_outliers=True,
    harmonise_units=True,

    var_order_menu = ['ang4487aer', 'od550aer', 'od550lt1aer', 'od550gt1aer',
                      'abs550aer', 'ac550aer', 'sc550dryaer'],
    var_mapping = VAR_MAPPING

)

COL_BASE = os.path.abspath('../../coldata/examples/')

EXP_ID = 'test-wetdep'

PROJ_SPECS = dict(

proj_id = 'examples',

#: ID and name of experiment
exp_id = EXP_ID,
exp_name = 'Example run to test wet deposition evaluation in CAMS61',

# directory where colocated data files are supposed to be stored
basedir_coldata = os.path.join(COL_BASE, EXP_ID),
weighted_stats = True

)

CFG = {}
CFG.update(PROJ_SPECS)
CFG.update(BASE_CFG)

CFG['model_config'] = {}
CFG['model_config'].update(MODELS)

CFG['obs_config'] = {}
CFG['obs_config'].update(OBS_GROUNDBASED)
CFG['obs_config'].update(OBS_SAT)

if __name__ == '__main__':
    import pyaerocom as pya
    from pyaerocom.web import AerocomEvaluation
    from pyaerocom.web.helpers_evaluation_iface import reorder_experiments_menu_evaluation_iface
    import matplotlib.pyplot as plt

    #assert pya.const.has_access_lustre
    plt.close('all')

    stp = AerocomEvaluation(try_load_json=False, **CFG)
    stp.to_json('.')
    print(stp)

    stp.run_evaluation()
```

**Comment by jgliss** [comment]
@hansbrenna I would like to merge this into `main-dev` before the workshop (and all other PR's that point to `main-dev`, so `main-dev` has the latest developments merged). I would appreciate if you could have a quick look. Some new functionality may miss docstrings and / or tests, but we will take care of those when drafting the release for 0.11.0 from `main-dev`... after the workshop.

**Comment by jgliss** [comment]
I think this needs some minor revisions before it can be merged, will look into it.

**Comment by jgliss** [comment]
@hansbrenna I think this can be reviewed as well now.

**Review by hansbrenna — APPROVED** [review]

**Pull request merged**
